source 'https://rubygems.org'

gem 'actionview'
gem 'bcrypt'
gem 'date_validator'
gem 'mysql2'
gem 'puma'
gem 'rack_csrf'
gem 'rack'
gem 'rake'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-flash'
gem 'sinatra'
gem 'slim'
gem 'thin'
